services:
  backend:
    build:
      context: ./backend
    container_name: finanzas-claras-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data

  frontend:
    build:
      context: ./frontend
    container_name: finanzas-claras-frontend
    environment:
      #VITE_API_URL: http://localhost:8000/api
      VITE_API_URL: http://192.168.100.9:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  sqlite_data:
